

services:
  web:
    build:
      context: ./web
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - bot
      - db
    env_file:
      - .env

  bot:
    build:
      context: ./bot
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: drivebot-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
