"""create all tables

Revision ID: 4b1a97b75508
Revises: 
Create Date: 2025-08-23 15:25:06.278398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1a97b75508'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('UNREGISTERED', 'DRIVER', 'ADMIN', name='role'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('additional_cities', sa.JSON(), nullable=False),
    sa.Column('car_brand', sa.String(length=100), nullable=True),
    sa.Column('car_model', sa.String(length=100), nullable=True),
    sa.Column('car_color', sa.String(length=50), nullable=True),
    sa.Column('car_number', sa.String(length=20), nullable=True),
    sa.Column('car_photo', sa.String(length=255), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('REGISTRATION', 'PENDING', 'APPROVED', 'DECLINED', name='status'), nullable=False),
    sa.Column('availability', sa.Enum('UNAVAILABLE', 'IN_WORK', name='availability'), nullable=False),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('completed_orders', sa.Integer(), nullable=False),
    sa.Column('cancelled_orders', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('scheduled_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('car_class', sa.String(length=50), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('mode', sa.Enum('FCFS', 'AUCTION', name='ordermode'), nullable=False),
    sa.Column('comments', sa.String(length=255), nullable=False),
    sa.Column('passenger_info', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'DONE', 'CANCELED', name='orderstatus'), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
