# Базовый образ Python
FROM python:3.13-slim

# Устанавливаем зависимости для сборки C-расширений
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
 && rm -rf /var/lib/apt/lists/*


# Рабочая директория
WORKDIR /app

# Копируем зависимости
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код бота
COPY . .

# Проброс порта для FastAPI (если бот принимает запросы)
EXPOSE 8001

# Команда запуска бота
CMD ["python", "main.py"]
